#!/bin/bash
kasutaja=$1
parool=$(pwgen 8 1)

mysql -e "CREATE DATABASE ${kasutaja};"
mysql -e "CREATE USER ${kasutaja}@localhost IDENTIFIED BY '$parool';"
mysql -e "GRANT ALL PRIVILEGES ON ${kasutaja}.* TO '${kasutaja}'@'localhost';"
mysql -e "FLUSH PRIVILEGES;"

touch /home/$kasutaja/.my.cnf
echo "[client]
user = $kasutaja
password = $parool
host = localhost" > /home/$kasutaja/.my.cnf
chmod 0600 /home/$kasutaja/.my.cnf
