#!/bin/bash

kasutajad=$1
paroolid=$2
for kasutaja in $(paste -d ":" $kasutajad $paroolid)
	do
	nimi=$( echo $kasutaja | cut -f1 -d ":" ) #nime definitsioon
	echo $kasutaja | chpasswd #määrab parooli
	done
