#!/bin/bash

PHP=$(dpkg-query -W -f='${status}' apache2 2>/dev/null | grep -c "ok installed")

if [ $PHP -eq 0 ]; then
	echo "Paigaldatakse PHP"
	apt-get install -y php5-mysql
	
elif [ $PHP -eq 1 ]; then
	echo "PHP on juba olemas."
fi
